// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElRow: typeof import('element-plus/es')['ElRow']
    Login: typeof import('./src/components/login.vue')['default']
    MainLayout: typeof import('./src/components/layout/mainLayout.vue')['default']
    MicroBar: typeof import('./src/components/layout/micro-bar.vue')['default']
    NavBar: typeof import('./src/components/layout/nav-bar.vue')['default']
  }
}

export { }
